modules_dir = "artifacts/"

[[module]]
    name = "ipfs_dag"
    mem_pages_count = 100
    logger_enabled = true

    [module.mounted_binaries]
    ipfs = "/usr/local/bin/ipfs"
    bash = "/bin/bash"

    [module.wasi]
    envs = { "/tmp/vault" = "./tmp" }
